### ISSUE TITLE
How to run and how the database looks like?

### ISSUE THREAD

**Issue by raditzlawliet** [bayyy7/mini-Microservice_Go#1]
Hi @bayyy7

I have trouble to try this project.
How to run this project and how the database looks like? 
Can you provide some information in readme and some SQL script to migrate the database?

**Comment by indrabayuu** [comment]
Thank you for checking it @raditzlawliet 

This repo is currently under development phase. I'll do my best to set it up and I'll put up dockerfile to making it easier
